version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Create Scratch Org
          command: . build/create-scratch-org.sh
      - run:
          name: Install Dependent Packages
          command: . build/install-dependent-packages.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/test.sh
      - store_test_results:
          path: test-results
  create-package-version:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Dev Hub
          command: . build/setup-dev-hub.sh
      - run:
          name: Create Package Version
          command: . build/create-package-version.sh
          no_output_timeout: 30m
  # deploy-prod:
  #   docker:
  #   - image: circleci/node:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Dependencies
  #         command: . build/install.sh
  #     - run:
  #         name: Login to Production
  #         command: . build/setup-prod.sh
  #     - run:
  #         name: Deploy to Production
  #         command: . build/deploy-prod.sh
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - create-package-version:
          filters:
            branches:
              only:
                - master